<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="1458" started-at="2016-04-28T08:39:19Z" finished-at="2016-04-28T08:39:21Z">
    <groups>
    </groups>
    <test name="test.ReadWebpage" duration-ms="1458" started-at="2016-04-28T08:39:19Z" finished-at="2016-04-28T08:39:21Z">
      <class name="test.ReadWebpage">
        <test-method status="FAIL" signature="RobotFile()[pri:0, instance:test.ReadWebpage@5c77399e]" name="RobotFile" duration-ms="1204" started-at="2016-04-28T14:09:19Z" finished-at="2016-04-28T14:09:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Disallow is present in the file]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Disallow is present in the file
	at org.testng.Assert.fail(Assert.java:94)
	at test.ReadWebpage.RobotFile(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.TestNG.privateMain(TestNG.java:1338)
	at org.testng.TestNG.main(TestNG.java:1307)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RobotFile -->
        <test-method status="PASS" signature="SecureSite()[pri:0, instance:test.ReadWebpage@5c77399e]" name="SecureSite" duration-ms="245" started-at="2016-04-28T14:09:21Z" finished-at="2016-04-28T14:09:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SecureSite -->
      </class> <!-- test.ReadWebpage -->
    </test> <!-- test.ReadWebpage -->
  </suite> <!-- Suite -->
</testng-results>
